### ISSUE TITLE
Composer requirements call for a non-existent version of sheadawson/silverstripe-blocks

### ISSUE THREAD

**Issue by mooror** [codecoyotes/silverstripe-ccblocks#1]
Hey there, I came across your repository and would love to incorporate it into some of my projects. Unfortunately I am having troubles installing the item as it requires "sheadawson/silverstripe-blocks": "^1.1", when sheadawson/silverstripe-blocks is only at version 1.0.12. Perhaps this was do to version refactoring on the project. Anyway could you change the version requirement to ^1.0 perhaps?

Thanks in advance,
Mooror

**Comment by michelsteege** [comment]
Hi,

There is a 1.1.x version of the blocks module see: https://packagist.org/packages/sheadawson/silverstripe-blocks
But i have to say, you are of course free to use this module but it is still in a very early development phase.

**Comment by mooror** [comment]
My apologies Michel, I was looking for the version 1.1.1 on the [blocks addon repository page](https://github.com/sheadawson/silverstripe-blocks/releases) and the first version I saw was version 1.0.12. When I went back to to double check after you posted your comment I noticed the small "show 4 newer tags" button. Which of course (when clicked) displayed four new versions with the latest being version 1.1.1. I will have to look better next time.

Thank you for your time,
Mooror

**Comment by mooror** [comment]
In response to the last line of your comment above. I just wanted to let you know that I understand the addon is in its early stages and that there might be bugs. I would like to use the addon as a foundation of sorts to build off of. I will make sure to to create pull requests for any bugs I fix.

Thanks again,
Mooror

**Comment by michelsteege** [comment]
Not a problem! good luck with your project 👍
